# Generated by Django 4.2.7 on 2023-11-29 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_game_console'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.game'),
            preserve_default=False,
        ),
    ]
